/* ----------------------------------------------
 * Generated by Animista on 2025-5-29 19:39:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        bebas: ["Bebas Neue", "sans-serif"],
        grotesk: ["Space Grotesk", "sans-serif"]
      },
      keyframes: {
        "text-focus-in": {
          "0%": {
            filter: 'blur(12px)',
            opacity: "0",
          },
          "100%": {
            filter: 'blur(0px)',
            opacity: "1",
          },
        },
      },
      animation: {
        "text-focus-in":
          "text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
      },
      colors: {
        nexus: {
          dark: "#1D1616",
          deep: "#8E1616",
          bright: "#D84040",
          light: "#EEEEEE",
        },
      }
    },
  },
  plugins: [],
};
